import { describe, expect, it } from "vitest";
import { InMemoryRetentionRepository } from "@/server/repositories/testing/in-memory-retention.repository";
import { RetentionWorker } from "@/server/workers/retention.worker";
const old = new Date("2026-01-01T00:00:00Z"); const recent = new Date("2026-08-22T00:00:00Z");
const repo = () => new InMemoryRetentionRepository({ media_upload_intents: [{ id: "old", eligibleAt: old }, { id: "new", eligibleAt: recent }], device_delivery_credentials: [{ id: "credential", eligibleAt: old }], worker_runs: [{ id: "run", eligibleAt: old }] });
describe("RetentionWorker", () => {
  it("defaults policy classes to skip and dry-run never deletes", async () => { const repository = repo(); const worker = new RetentionWorker(repository, { enabled: false, days: { media_upload_intents: 30 } }, { workerId: "a", now: () => new Date("2026-08-23T00:00:00Z") }); const result = await worker.run({ dryRun: true, limit: 1 }); expect(result.classes[0]).toMatchObject({ eligible: 1, deleted: 0 }); expect(result.classes[1]).toMatchObject({ status: "skipped" }); expect(repository.rows.media_upload_intents).toHaveLength(2); });
  it("requires explicit enable and deletes only bounded eligible rows", async () => { const repository = repo(); const disabled = new RetentionWorker(repository, { enabled: false, days: { worker_runs: 1 } }, { workerId: "a" }); await expect(disabled.run({ dryRun: false, limit: 1 })).rejects.toMatchObject({ status: 409 }); const enabled = new RetentionWorker(repository, { enabled: true, days: { media_upload_intents: 30 } }, { workerId: "a", now: () => new Date("2026-08-23T00:00:00Z") }); const result = await enabled.run({ dryRun: false, limit: 1 }); expect(result.classes[0]).toMatchObject({ deleted: 1 }); expect(repository.rows.media_upload_intents.map((item) => item.id)).toEqual(["new"]); });
  it("allows only one live lease", async () => { const repository = repo(); repository.lease = { owner: "peer", expiresAt: new Date("2099-01-01") }; const worker = new RetentionWorker(repository, { enabled: false, days: {} }, { workerId: "other", now: () => new Date("2026-01-01") }); await expect(worker.run({ dryRun: true, limit: 25 })).resolves.toMatchObject({ status: "busy", classes: [] }); });
});
